<?xml version="1.0"?>
<package format="2">
  <name>echo_q_slam</name>
  <version>1.0.0</version>
  <description>GMapping SLAM for ECHO-Q.</description>
  <maintainer email="shreyas@example.com">Shreyas S Rai</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>gmapping</exec_depend>
</package>
